### ISSUE TITLE
Our Twitter timeline now shows 'Tweets by ‎@twitterapi'

### ISSUE THREAD

**Issue by sensibleandy** [rainlab/twitter-plugin#14] opened 2016-07-21 18:18 UTC
Hi, I integrated your plugin successfully into our October CMS web site (www.pentathlongb.org) a few weeks ago to display our tweets, but now tweets from @twitterapi are being displayed instead.

Is there anything that can be done to fix the problem please?

Thanks,

Andy

**Comment by wvelez6** [comment] 2016-07-26 13:47
@sensibleandy I saw on your site above that you managed to fix your issue with the plugin displaying the @twitterapi. How you manage to fix it? I have the same issue.

**Comment by wvelez6** [comment] 2016-07-26 14:54
Never mind figured it out, for those with this issue in the future, which is not an issue, you need to get your twitter widget id number and provide the plugin with the number.

**Comment by daftspunk** [comment] 2016-07-27 09:20
This looks like a duplicate of #13

@wvelez6 Can you tell us how you found the widget id number?

**Comment by wvelez6** [comment] 2016-07-27 20:06
@daftspunk Under Twitter Settings click on Widgets, click on edit on the widget you want. In that page you should see an html embed code and there you will see  data-widget-id="123456789876543212">, copy the number and place under the WidgetID of the Twitter plugin.

**Comment by daftspunk** [comment] 2016-07-28 08:40
Thanks @wvelez6 please continue the conversation in #13

**Closed as completed by daftspunk** 2016-07-28 08:40 UTC
Labels: duplicate
